services:
  - type: web
    name: matrass
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh start.sh && ./build.sh
    preDeployCommand: python manage.py migrate --no-input
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
