# Generated by Django 6.0.5 on 2026-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Атауы (RU)')),
                ('name_kk', models.CharField(blank=True, max_length=200, verbose_name='Атауы (KZ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Атауы (EN)')),
                ('description_ru', models.TextField(verbose_name='Сипаттама (RU)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Сипаттама (KZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Сипаттама (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Сурет')),
                ('image_url', models.URLField(blank=True, verbose_name='Сурет сілтемесі')),
                ('price', models.PositiveIntegerField(verbose_name='Қазіргі баға (₸)')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Бұрынғы баға (₸)')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Қазіргі жеңілдік (%)')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Акция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Көрсету')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Реті')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товарлар',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
